### ISSUE TITLE
it throws E20 errs 7 times

### ISSUE THREAD

**Issue by edisonX-sudo** [kehr/krc#1]
info such like 
" \* @File Name:    /Users/wangkaixuan/.vimrc
- @Author:       kehr
- @Mail:         kehr.china@gmail.com
- @Created Time: 日, 04/26/2015, 21时25分18秒
- @Copyright:    GPL 2.0
- @Description:  
  *************************************************************************/"
  should be dealed in a proper way.it throws E20 errs 7 times in my os X yosemite .it works when I cut it away

**Comment by kehr** [comment]
This is my mistake :(

I have fixed this bug at https://github.com/kehr/krc/commit/1c3f709ad29767b28a64eab85bfddf21efe51c8f

Thanks your issue. that's awesome !
